### ISSUE TITLE
Flipbook not working

### ISSUE THREAD

**Issue by colin1715labs** [1715labs/1715labs-pfe#17]
## Expected behaviour

When using flipbook, expect crowd to be able to be able to click between frames and play frames going from one to the other

![image](https://user-images.githubusercontent.com/61154605/113852170-2bc1b080-9794-11eb-9119-2b9b38e8486d.png)

## Current behaviour

Only first frame shows - the buttons below to move between pages of the flip book do not show 

![image](https://user-images.githubusercontent.com/61154605/113852058-0765d400-9794-11eb-8545-36f36d6070d6.png)

## Additional information

- **Operating system:** Mac and PC
- **Browser:** Chrome

**Comment by tingard** [comment]
Closing as this has been fixed (@rogerhutchings )
