### ISSUE TITLE
Polygons should only close when completed

### ISSUE THREAD

**Issue by tingard** [1715labs/1715labs-pfe#19]
## Expected behaviour

The polygon tool should only close when the worker clicks on the initial marking, completing the loop.

## Current behaviour
Closing a polygon can be done by clicking on the starting point *or* the most recent marking, leading to accidental polygon closure for high-resolution polygons.

**Comment by rogerhutchings** [comment]
Side effects:

- This will affect behaviour for all projects using this polygon tool - we'll have to revert this change if we want things to go back
- It'll be possible to submit unclosed polygons

**Comment by tingard** [comment]
Is it not already possible to submit unclosed polygons?

**Comment by rogerhutchings** [comment]
I can't remember if it closes them automagically. Probably not, come to think of it

**Comment by rogerhutchings** [comment]
IT TOTALLY DOES

**Comment by tingard** [comment]
Is that desired behaviour? Should we allow the submission of unclosed polygons?

**Comment by rogerhutchings** [comment]
If you have an open polygon and click "Done", it gets closed

**Comment by rogerhutchings** [comment]
On reflection, changing this wouldn't have affected that either way, derp
