### ISSUE TITLE
The tutorial should be wider

### ISSUE THREAD

**Issue by tingard** [1715labs/1715labs-pfe#63]
Tutorial width is currently clipped at 400px

It would be great if this could be much wider - say 1200px or simply relative to screen width.

I hope that this can be achieved by just changing this line of code (not tested) https://github.com/1715labs/1715labs-pfe/blob/008af41ae5f6f1e11a071d92454772c9374005bf/css/tutorial.styl#L29

**Comment by tingard** [comment]
There are a load of other references to "400px" in the Zooniverse codebase, which concerns me a little as they could tie back to this - but only one way to find out! 🤞

**Comment by rogerhutchings** [comment]
#67
